const AETHERWOOD_CONFIG = {
  SCRIPT_URL: "PASTE_YOUR_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE",
  CLOUDINARY_CLOUD_NAME: "PASTE_YOUR_CLOUDINARY_CLOUD_NAME_HERE",
  CLOUDINARY_UPLOAD_PRESET: "PASTE_YOUR_UNSIGNED_UPLOAD_PRESET_HERE",
  FAMILY_CODE: "dadrew"
};
